WebPresentation/Controllers/ForumController.cs
/// <summary>
/// Creator: Jackson Manternach
/// Created: 2025/04/07
/// Summary: Controller class to handle forum code
///
/// Last Updated By: Skyann Heintz
/// Last Updated: 2025/04/18
/// What Was Changed: Added ForumPermissionManager related items. Added CreateThread code.
/// Last Updated By: Dat Tran
/// Last Updated: 2025/04/27
/// What Was Changed: Added TempData for Sweet Alert.
/// </summary>


using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using DataDomain;
using LogicLayer;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Identity;

namespace WebPresentation.Controllers
{
    public class ForumController : Controller
    {
        private readonly IThreadManager _threadManager = new ThreadManager();
        private readonly IProjectManager _projectManager = new ProjectManager();
        private readonly IForumPermissionManager _forumPermissionManager = new ForumPermissionManager();
        private SignInManager<IdentityUser> _signInManager;

        public ForumController(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        private LogicLayer.IUserManager _userManagerLogic = new UserManager();
        private Models.AccessToken _accessToken = new Models.AccessToken("");

        private void getAccessToken()
        {

            if (_signInManager.IsSignedIn(User))
            {
                string email = User.Identity.Name;
                try
                {
                    _accessToken = new Models.AccessToken(email);
                }
                catch { }
            }
            else
            {
                return;
            }
        }

        /// <summary>
        /// Creator: Jackson Manternach
        /// Created: 2025/04/07
        /// Summary: Method to get all threads and project information, includes default information in case a project
        /// is not found
        ///
        /// Last Updated By:
        /// Last Updated:
        /// What Was Changed:
        /// </summary>
        public IActionResult ViewProjectForum(int id)
        {
            getAccessToken();
            if (!_accessToken.IsLoggedIn ||
                (!_accessToken.HasProjectRole("Volunteer", id) &&
                !_accessToken.HasProjectRole("Project Starter", id)
                ))
            {
                return RedirectToAction("AccessDenied", "Home");
            }

            try
            {
                var threads = _threadManager.GetThreadsByProjectID(id);
                var project = _projectManager.GetProjectByID(id);

                ViewBag.ProjectName = project?.Name ?? "Project";
                ViewBag.ProjectID = id;

                return View(threads);
            }
            catch (Exception)
            {
                ViewBag.ProjectName = "Project";
                ViewBag.ProjectID = id;
                return View(new List<ThreadVM>());
            }
        }
        /// <summary>
        /// Creator: Skyann Heintz
        /// Created: 2025/04/18
        /// Summary: Method to create a new thread
        ///
        /// Last Updated By:
        /// Last Updated:
        /// What Was Changed:
        /// </summary>
        public ActionResult CreateThread(int userID, int projectID)
        {
            getAccessToken();
            if (!_accessToken.IsLoggedIn ||
                (!_accessToken.HasProjectRole("Volunteer", projectID) &&
                !_accessToken.HasProjectRole("Project Starter", projectID)
                ))
            {
                return RedirectToAction("AccessDenied", "Home");
            }

            userID = _accessToken.UserID;
            var project = _projectManager.GetProjectByID(projectID);
            var datePosted = DateTime.Now;

            var thread = new ThreadVM
            {
                UserID = userID,
                ProjectID = projectID,
                DatePosted = datePosted
            };

            ViewBag.ProjectID = projectID;
            return View(thread);
        }

        /// <summary>
        /// Creator: Skyann Heintz
        /// Created: 2025/04/18
        /// Summary: Method to create a new thread
        ///
        /// Last Updated By:
        /// Last Updated:
        /// What Was Changed:
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateThread(int userID, string content, int projectID, string threadName, DateTime datePosted)
        {
            ViewBag.ProjectID = projectID;
            try
            {
                if (!_forumPermissionManager.SelectUserWriteAccess(userID, projectID))
                {
                    ModelState.AddModelError("", "You do not have permission to post in this project forum.");
                    return View(new ThreadVM
                    {
                        UserID = userID,
                        Content = content,
                        ProjectID = projectID,
                        ThreadName = threadName,
                        DatePosted = datePosted
                    });
                }

                if (ModelState.IsValid)
                {
                    bool success = _threadManager.InsertForumPost(userID, content, projectID, threadName, datePosted);
                    TempData["SuccessMessage"] = "Project Thread created.";
                    return RedirectToAction("ViewProjectForum", new { id = projectID });

                }

                return View(new ThreadVM
                {
                    UserID = userID,
                    Content = content,
                    ProjectID = projectID,
                    ThreadName = threadName,
                    DatePosted = datePosted
                });

            }

            catch (Exception ex)
            {
                ModelState.AddModelError("", "An unexpected error occurred while trying to create the thread. Please try again later.");

                return View(new ThreadVM
                {
                    UserID = userID,
                    Content = content,
                    ProjectID = projectID,
                    ThreadName = threadName,
                    DatePosted = datePosted
                });

            }
        }
    }
}

WebPresentation/Controllers/PostsController.cs
/// <summary>
/// Creator: Nik Bell
/// Created: 2025-04-18
/// Summary:
///     A controller that handles navigation to the proper views
///     related to forum posts for a project.
/// 
/// Last Updated By: Kate Rich
/// Last Updated: 2025-04-18
/// What Was Changed:
///     Updated the Index() method parameter to just be 'id', so that it can
///     properly handle values being passed to it from this & other Controller
///     classes.
/// Last Updated By: Skyann Heintz
/// Last Updated: 2025-04-18
/// What Was Changed:
///     Added method to edit the user's own posts. I also updated the create to reload the thread properly.
///     As it was directing back to a blank view.
///     
/// Last Updated By: Syler Bushlack
/// Last Updated: 2025-04-24
/// What Was Changed:
///     Added pin method to pin posts and added validation to check if user has permision to create a post
///     
/// Last Updated By: Dat Tran
/// Last Updated: 2024-04-26
/// What was changed: Added TempData for Sweet Alert CRUD functions.   
/// </summary>

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using LogicLayer;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;
using DataDomain;
using Microsoft.AspNetCore.Identity;
using Microsoft.CodeAnalysis;

namespace WebPresentation.Controllers
{
    public class PostsController : Controller
    {
        IPostManager _postManager = new PostManager();
        IForumPermissionManager _forumPermissionManager = new ForumPermissionManager();
        private SignInManager<IdentityUser> _signInManager;
        IThreadManager _threadManager = new ThreadManager();

        public PostsController(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        private LogicLayer.IUserManager _userManagerLogic = new UserManager();
        private Models.AccessToken _accessToken = new Models.AccessToken("");

        private void getAccessToken()
        {

            if (_signInManager.IsSignedIn(User))
            {
                string email = User.Identity.Name;
                try
                {
                    _accessToken = new Models.AccessToken(email);
                }
                catch { }
            }
            else
            {
                return;
            }
        }

        // GET: PostsController
        public ActionResult Index(int id, int projectID)
        {
            getAccessToken();
            if (!_accessToken.IsLoggedIn ||
                (!_accessToken.HasProjectRole("Volunteer", projectID) &&
                !_accessToken.HasProjectRole("Project Starter", projectID) &&
                !_accessToken.HasProjectRole("Volunteer Director", projectID) &&
                !_accessToken.HasProjectRole("Event Coordinator", projectID) &&
                !_accessToken.HasProjectRole("Moderator", projectID) &&
                !_accessToken.HasProjectRole("Scheduler", projectID) &&
                !_accessToken.HasProjectRole("Driver", projectID) &&
                !_accessToken.HasProjectRole("Accountant", projectID) &&
                !_accessToken.HasProjectRole("Purchaser", projectID) &&
                !_accessToken.HasProjectRole("Background Checker", projectID))
                )
            {
                return RedirectToAction("AccessDenied", "Home");
            }

            ViewBag.threadId = id;
            ViewBag.projectID = projectID;
            var posts = _postManager.GetAllThreadPosts(id);
            return View(posts);
        }

        // GET: PostsController/Create
        public ActionResult Create(int id, int projectID)
        {
            getAccessToken();
            if (!_accessToken.IsLoggedIn ||
                (!_accessToken.HasProjectRole("Volunteer", projectID) &&
                !_accessToken.HasProjectRole("Project Starter", projectID) &&
                !_accessToken.HasProjectRole("Volunteer Director", projectID) &&
                !_accessToken.HasProjectRole("Event Coordinator", projectID) &&
                !_accessToken.HasProjectRole("Moderator", projectID) &&
                !_accessToken.HasProjectRole("Scheduler", projectID) &&
                !_accessToken.HasProjectRole("Driver", projectID) &&
                !_accessToken.HasProjectRole("Accountant", projectID) &&
                !_accessToken.HasProjectRole("Purchaser", projectID) &&
                !_accessToken.HasProjectRole("Background Checker", projectID))
                )
            {
                return RedirectToAction("AccessDenied", "Home");
            }

            if (id > 0)
            {
                ViewBag.threadId = id;
            }
            ViewBag.projectID = projectID;

            return View();
        }

        // POST: PostsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
            getAccessToken();
            // TODO: Replace with login system
            post.UserID = _accessToken.UserID;

            if (ModelState.IsValid)
            {
                try
                {
                    if (!_forumPermissionManager.SelectUserWriteAccess(post.UserID, post.ProjectID))
                    {
                        ModelState.AddModelError("", "You do not have permission to post in this project forum.");
                        ViewBag.threadId = post.ThreadID;
                        return View(post);
                    }
                    IPostManager postManager = new PostManager();

                    _postManager.CreateForumPost(post);
                    TempData["AddSuccess"] = "Thread post created successfully!";
                    return RedirectToAction(nameof(Index), new { id = post.ThreadID, projectID = post.ProjectID });
                }
                catch (Exception ex)
                {
                    // Optionally log or show error
                    ModelState.AddModelError("", "Error creating post: " + ex.Message);
                    return View(post);
                }
            }
            ViewBag.ProjectID = post.ProjectID;
            return View(post);
        }

        /// <summary>
        /// Creator: Skyann Heintz
        /// Created: 2025/04/18
        /// Summary: Method to edit a post. 
        ///
        /// Last Updated By: Skyann Heintz
        /// Last Updated: 2025-04-28
        /// What Was Changed: Added  ViewBag.ThreadID = post.ThreadID; so that
        ///     the user to go back to the same list when hitting the back button on the view.
        /// </summary>
        public ActionResult Edit(int id, int projectID)
        {
            try
            {
                var post = _postManager.SelectPostByID(id);

                getAccessToken();
                if (!_accessToken.IsLoggedIn ||
                    _accessToken.UserID != post.UserID
                    )
                {
                    return RedirectToAction("AccessDenied", "Home");
                }

                if (post == null)
                {
                    return NotFound();
                }
                ViewBag.ThreadID = post.ThreadID;
                ViewBag.ProjectID = projectID;
                return View(post);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error loading post: " + ex.Message);
                return View();
            }

        }

        /// <summary>
        /// Creator: Skyann Heintz
        /// Created: 2025/04/18
        /// Summary: Method to edit a post. 
        ///
        /// Last Updated By:
        /// Last Updated:
        /// What Was Changed:
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit (int postID, Post post, int projectID)
        {
            try
            {
                var updatePosts = new Post();

                updatePosts.PostID = postID;
                Post oldPost = _postManager.SelectPostByID(postID);

                if (ModelState.IsValid)
                {
                    bool updatedPosts = _postManager.EditForumPost(postID, oldPost.UserID, post.Content);
                    TempData["SuccessMessage"] = "Post updated successfully.";
                    return RedirectToAction(nameof(Index), new { id = oldPost.ThreadID, projectID = post.ProjectID });

                }
                else
                {
                    return View(post);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred: " + ex.Message);
                return View(post);
            }
        }

        // GET: PostsController/Delete/5
        public ActionResult Delete(int id, int projectID)
        {
            var post = _postManager.SelectPostByID(id); // You must retrieve the post to get threadID

            getAccessToken();
            if (!_accessToken.IsLoggedIn ||
                (!_accessToken.HasProjectRole("Moderator", projectID) &&
                _accessToken.UserID != post.UserID)
                )
            {
                return RedirectToAction("AccessDenied", "Home");
            }

            if (_postManager.DeleteForumPost(id))
            {
                TempData["DeleteSuccess"] = "Post was deleted.";
                return RedirectToAction("Index", new { id = post.ThreadID, projectID = projectID });
            }
            else
            {
                return View("Error");
            }
        }

        // POST: PostsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // Author: Syler Bushlack

WebPresentation/Views/Forum/CreateThread.cshtml
@*<summary> *@
@* Creator: Skyann Heintz  *@
@* Created: 2025-04-18  *@
@* Summary: Create Thread Page *@
@* *@
@* Last Updated By: Syler Bushlack*@
@* Last Updated: 2025-04-24*@
@* What Was Changed: *@
@*      Changed Back to List to pass the projectID to the ViewProjectForum *@
@* Last Updated By: Skyann Heintz*@
@* Last Updated: 2025-04-28*@
@* What Was Changed: *@
@*      Updated styling.
@* </summary> *@
@model DataDomain.Thread

@{
    ViewData["Title"] = "CreateThread";
    int projectID = ViewBag.ProjectID;
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm p-4">
                <h2 class="text-center mb-4">Create Thread</h2>

                <form asp-action="CreateThread">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="ThreadID" class="control-label" hidden></label>
                        <input asp-for="ThreadID" class="form-control" hidden />
                        <span asp-validation-for="ThreadID" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectID" class="control-label" hidden></label>
                        <input asp-for="ProjectID" class="form-control" hidden />
                        <span asp-validation-for="ProjectID" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserID" class="control-label" hidden></label>
                        <input asp-for="UserID" class="form-control" hidden />
                        <span asp-validation-for="UserID" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ThreadName" class="control-label">Thread Name</label>
                        <input asp-for="ThreadName" class="form-control" />
                        <span asp-validation-for="ThreadName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DatePosted" class="control-label" hidden></label>
                        <input asp-for="DatePosted" class="form-control" hidden />
                        <span asp-validation-for="DatePosted" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Content" class="control-label"></label>
                        <input asp-for="Content" class="form-control" />
                        <span asp-validation-for="Content" class="text-danger"></span>
                    </div>
                    <div class="form-group text-center mt-4">
                        <input type="submit" value="Create" class="btn btn-success" />
                        <a asp-action="ViewProjectForum" asp-route-id="@projectID" class="btn btn-secondary ml-3">Back to Project Forum</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@* <div> *@
@*     @* <a asp-action="ViewProjectForum" asp-route-id="projectID">Back to List</a> *@ 
@*     @Html.ActionLink("Back to List", "ViewProjectForum", new { id = projectID }) *@
@* </div> *@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebPresentation/Views/Forum/ViewProjectForum.cshtml
<!--
/// <summary>
/// Creator: Jackson Manternach
/// Created: 2025/04/07
/// Summary: View for a project's forum, displays threads for a specific project
///
/// Last Updated By: Nik Bell & Kate Rich
/// Last Updated: 2025-04-18
/// What Was Changed: Updated the link to the Details view to route to the PostsController's Index method.
///
/// Last Updated By: Syler Bushlack
/// Last Updated: 2025-04-24
/// What Was Changed: Added link to mute volunteers page and changed the details link to include the projectID
///
/// Last Updated By: Skyann Heintz
/// Last Updated: 2025-04-28
/// What Was Changed: Added styling
///
/// Last Updated By: Dat Tran
/// Last Updated: 2025-04-27
/// What Was Changed: Added Sweet Alert for creating a project forum.
/// </summary>
-->
@model IEnumerable<DataDomain.ThreadVM>

@{
    ViewData["Title"] = "Project Forum";
}

<div class="text-center mb-4">
    <h1>Welcome to the @ViewBag.ProjectName Forum!</h1>
</div>
@if (TempData["SuccessMessage"] != null)
{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            if (!sessionStorage.getItem('sweetAlertCreateThreadShown')) {
                Swal.fire({
                    icon: 'success',
                    title: 'Done',
                    text: '@TempData["SuccessMessage"]'
                });
                sessionStorage.setItem('sweetAlertCreateThreadShown', 'true');
            }
        });
    </script>
    @* Remove the message so it doesn’t persist on refresh *@
    TempData.Remove("SuccessMessage");
}
else
{
    <script>
        // Ensure the flag is reset if there's no success message
        sessionStorage.removeItem('sweetAlertCreateThreadShown');
    </script>
}

<div class="mb-3 d-flex gap-2">
    <a asp-controller="Forum" class="btn btn-success" asp-action="CreateThread" asp-route-projectId="@ViewBag.ProjectID">Create New Thread</a>
    <a href="@Url.Action("Index", "ForumPermission", new { projectID = ViewBag.ProjectID })" class="btn btn-info">Mute Volunteers</a>

</div>



@if (Model != null && Model.Any())
{
    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th class="header">Thread Name</th>
                <th class="header">Posted By</th>
                <th class="header">Date Posted</th>
                <th class="header"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var thread in Model)
            {
                <tr>
                    <td>@thread.ThreadName</td>
                    <td>@thread.GivenName @thread.FamilyName</td>
                    <td>@thread.DatePosted.ToShortDateString()</td>
                    <td>
                        <div class="d-flex flex-wrap justify-content-center gap-2">
                            <a asp-controller="Posts" asp-action="Index" asp-route-id="@thread.ThreadID" asp-route-projectID="@ViewBag.ProjectID" class="btn btn-primary btn-sm">Details</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info text-center">No threads found for this project.</div>
}