WebPresentation/Controllers/UserController.cs
/// <summary>
/// Creator:  Jacob McPherson
/// Created:  2025/03/29
/// Summary:  The controller for users
/// 
/// Updated By: Jacob McPherson
/// Updated: 2025/04/24
/// What was Changed: Added Deactivate
/// 
/// Last Updated By: Kate Rich
/// Last Updated: 2025-04-26
/// What Was Changed:
///     Removed the Index() method from this controller & placed it back in the AdminController.
/// 
/// </summary>
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using DataDomain;
using LogicLayer;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace WebPresentation.Controllers
{
    public class UserController : Controller
    {
        UserManager _userManager = new UserManager();

        private readonly UserManager<IdentityUser> _identityManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public UserController(UserManager<IdentityUser> identityManager, SignInManager<IdentityUser> signInManager)
        {
            _identityManager = identityManager;
            _signInManager = signInManager;
        }

        private LogicLayer.IUserManager _userManagerLogic = new UserManager();
        private Models.AccessToken _accessToken = new Models.AccessToken("");

        private void getAccessToken()
        {

            if (_signInManager.IsSignedIn(User))
            {
                string email = User.Identity.Name;
                try
                {
                    _accessToken = new Models.AccessToken(email);
                }
                catch { }
            }
            else
            {
                return;
            }
        }

        // GET: UserController/Details/5
        [Authorize]
        public ActionResult UserProfile(string email)
        {
            User user = new User();

            user = _userManager.RetrieveUserDetailsByEmail(email);
            user.PasswordHash = "";
            return View(user);
        }

        // GET: UserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Delete/5
        [Authorize]
        public ActionResult Delete()
        {
            ViewBag.Error = "";

            return View();
        }

        // POST: UserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Delete(IFormCollection collection)
        {
            try
            {
                bool success = _userManager.DeactivateUser(GetUserEmail(), collection["password"]);

                if (!success)
                {
                    throw new ArgumentException("Wrong Password Or Email");
                }

                _signInManager.SignOutAsync();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                ViewBag.Error = "Wrong Password";

                return View();
            }
        }

        /// <summary>
        /// Creator:  Jacob McPherson
        /// Created:  2025/04/24
        /// Summary:  Gets Email of Current User
        /// Last Updated By:
        /// Last Updated: 
        /// What was Changed: 	
        /// </summary>
        private string GetUserEmail()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId == null)
            {
                return null;
            }

            var user = _identityManager.FindByIdAsync(userId).Result;

            if (user == null)
            {
                return null;
            }

            return user.Email;
        }
    }
}

WebPresentation/Controllers/VehicleController.cs
/// <summary>
/// Ellie Wacker
/// Created: 2025-03-27
/// 
/// Controller for the Vehicle class.
/// </summary>

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using LogicLayer;
using DataDomain;
using System.Text.RegularExpressions;
using System.Diagnostics;
using Tesseract;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace WebPresentation.Controllers
{
    public class VehicleController : Controller
    {
        private IVehicleManager _manager = new VehicleManager();
        private IDocumentManager _docManager = new DocumentManager();
        IUserSystemRoleManager _userSystemRoleManager = new UserSystemRoleManager();
        List<UserSystemRole> _userSystemRoles = new List<UserSystemRole>();
        private IUserManager _userManager = new UserManager();
        private SignInManager<IdentityUser> _signInManager;

        public VehicleController(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        private LogicLayer.IUserManager _userManagerLogic = new UserManager();
        private Models.AccessToken _accessToken = new Models.AccessToken("");

        private void getAccessToken()
        {

            if (_signInManager.IsSignedIn(User))
            {
                string email = User.Identity.Name;
                try
                {
                    _accessToken = new Models.AccessToken(email);
                }
                catch { }
            }
            else
            {
                return;
            }
        }

        /// <summary>
        /// Ellie Wacker
        /// Created: 2025/03/27
        /// 
        /// GET: VehicleController
        /// The Controller method for getting all vehicles
        /// </summary>
        ///
        /// <remarks>
        /// Updater Name
        /// Updated: yyyy/mm/dd 
        /// example: Fixed a problem when user inputs bad data
        /// </remarks> 
        [Authorize]
        public ActionResult Index(int id)
        {
            User user = _userManager.GetUserInformationByUserID(id);
            ViewBag.Email = user.Email;
            try
            {
                _userSystemRoles = _userSystemRoleManager.GetUserSystemRolesByUserID(id);
            }
            catch
            {

            }
            try
            {
                ViewBag.UserID = id;
                var vehicles = _manager.GetVehiclesByUserID(id);

                if (vehicles == null)
                {
                    vehicles = new List<Vehicle>();
                    ViewBag.Message = "You don't have any vehicles at this time.";
                }
                else if (!vehicles.Any())
                {
                    ViewBag.Message = "You don't have any vehicles at this time.";
                }

                return View(vehicles);
            }
            catch (Exception ex)
            {
                string message = ex.InnerException == null ? ex.Message : ex.Message + "\n\n" + ex.InnerException.Message;
                ViewBag.Message = "You don't have any vehicles at this time.";
                return View();
            }

        }

        /// <summary>
        /// Ellie Wacker
        /// Created: 2025/03/27
        /// 
        /// GET: VehicleController/Details/5
        /// The Controller method for getting a detailed view of a vehicle
        /// </summary>
        ///
        /// <remarks>
        /// Updater Name
        /// Updated: yyyy/mm/dd 
        /// example: Fixed a problem when user inputs bad data
        /// </remarks> 
        [Authorize]
        public ActionResult Details(int id)
        {
            return View();
        }

        /// <summary>
        /// Ellie Wacker
        /// Created: 2025/03/27
        /// 
        /// The Controller method for populating drop downs
        /// </summary>
        ///
        /// <remarks>
        /// Updater Name
        /// Updated: yyyy/mm/dd 
        /// example: Fixed a problem when user inputs bad data
        /// </remarks> 
        private void populateDropDowns()
        {
            List<string> TransportItems = new List<string>()
            {
               "Adults",
               "Children",
               "Animals",
               "Equipment",
               "Grocercies",
               "Plants",
               "Dirt/Sand/Salt",
               "Rocks",
               "Appliances",
               "Oil",
               "Paint/Sealers/Stain"
            };
            ViewBag.TransportItems = TransportItems;
        }

        /// <summary>
        /// Ellie Wacker
        /// Created: 2025/03/27
        /// 
        /// The Controller get method for creating a vehicle
        /// </summary>
        ///
        /// <remarks>
        /// Updater Name
        /// Updated: yyyy/mm/dd 
        /// example: Fixed a problem when user inputs bad data
        /// </remarks> 
        // GET: VehicleController/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            ViewBag.UserID = id;
            populateDropDowns();
            return View();
        }


        /// <summary>
        /// Ellie Wacker
        /// Created: 2025/03/27
        /// 
        /// The Controller post method for creating a vehicle
        /// </summary>
        ///
        /// <remarks>
        /// Updater Name
        /// Updated: yyyy/mm/dd 
        /// example: Fixed a problem when user inputs bad data
        /// </remarks> 
        /// Updated By: Dat Tran
        /// Updated: 2025-04-27
        /// What was changed: Changed the REGEX of license plate numbers to work with optional spaces and dashes. Added
        /// TempData for adding a vehicle to use with Sweet Alert. 
        /// 
        /// Updated By: Dat Tran
        /// Updated: 2025-05-01
        /// What was changed: Changed the REGEX of license plate numbers to be less strict on the format. 
        // POST: VehicleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vehicle vehicle, int id)
        {
            ViewBag.UserID = id;
            //regex source = https://stackoverflow.com/questions/19547061/regex-representation-for-licence-plate
            string licensePlateRegex = @"^[A-Z0-9]+([- ][A-Z0-9]+)*$";
            Regex validLicensePlate = new Regex(licensePlateRegex);

            string VINRegex = @"^[A-HJ-NPR-Z0-9]{17}$";
            Regex validVIN = new Regex(VINRegex);

            if (vehicle.Make.Length < 3 || vehicle.Make.Length > 50)
            {
                ModelState.AddModelError("Make", "Invalid Vehicle Make.");
            }

            if (vehicle.Model.Length < 3 || vehicle.Model.Length > 50)
            {
                ModelState.AddModelError("Model", "Invalid Vehicle Model.");
            }

            int currentYear = DateTime.Now.Year;
            if (vehicle.Year < 1886 || vehicle.Year > currentYear + 1)
            {
                ModelState.AddModelError("Year", "Invalid Vehicle Year.");
            }

            if (vehicle.Color.Length < 3 || vehicle.Color.Length > 20)
            {
                ModelState.AddModelError("Color", "Invalid Vehicle Color.");
            }

            if (vehicle.NumberOfSeats < 1 || vehicle.NumberOfSeats > 60) //Standard coach bus seat number
            {
                ModelState.AddModelError(nameof(vehicle.NumberOfSeats), "Invalid Number of Seats.");
            }

            if (!validLicensePlate.IsMatch(vehicle.LicensePlateNumber))
            {
                ModelState.AddModelError(nameof(vehicle.LicensePlateNumber), "Invalid License Plate Number.");
            }

            string licensePlateNumber = vehicle.LicensePlateNumber.Replace("-", "").Replace(" ", ""); // removes dashes/spaces
            if (licensePlateNumber.Length > 7)
            {
                ModelState.AddModelError(nameof(vehicle.LicensePlateNumber), "License Plate Number must be 7 characters or less.");
            }
            if (!validVIN.IsMatch(vehicle.VehicleID))
            {
                ModelState.AddModelError(nameof(vehicle.VehicleID), "Invalid VIN Number.");

            }
            if (_manager.GetAllVehicles().Any(existingVehicle => existingVehicle.VehicleID == vehicle.VehicleID.Trim()))
            {
                ModelState.AddModelError("VehicleID", "A vehicle with that VIN number already exists.");
            }


            if (!vehicle.InsuranceStatus)
            {
                ModelState.AddModelError("InsuranceStatus", "Your vehicle must be insured");

            }

            try
            {
                if (ModelState.IsValid)
                {
                    string[] transportOptions = Request.Form["TransportUtility"];
                    vehicle.TransportUtility = string.Join(",", transportOptions);
                    TempData["AddSuccess"] = "Vehicle successfully added.";
                    _manager.InsertVehicle(vehicle.VehicleID, id, false, vehicle.Color, vehicle.Year, licensePlateNumber, vehicle.InsuranceStatus, vehicle.Make, vehicle.Model, vehicle.NumberOfSeats, vehicle.TransportUtility);
                    return RedirectToAction(nameof(Index), new { id = id });
                }
                else
                {
                    Console.WriteLine("ModelState is invalid. Errors:");
                    foreach (var entry in ModelState)
                    {
                        foreach (var error in entry.Value.Errors)
                        {
                            Console.WriteLine($"Field: {entry.Key}, Error: {error.ErrorMessage}");
                        }
                    }

                    return View(vehicle);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error", ex);
                return View();
            }
        }


        /// <summary>

WebPresentation/Views/Vehicle/AddLicense.cshtml
<!--
    /// <summary>
    /// Creator: Ellie Wacker
    /// Created: 2025-04-03
    /// Summary: View for adding a driver license image
    ///
    /// Updated By: Skyann Heintz
    /// Updated: 2025-04-27
    /// What Was Changed: Styling was added to the page.
    ///
    /// Updated By: Skyann Heintz
    /// Updated: 2025-04-30
    /// What Was Changed: Updated button from "Save" to "Add" to match the other button. 
            Updated "Back to Profile" to "Back to Vehicles"
-->
@using DataDomain
@model Vehicle

@{
    ViewData["Title"] = "Add License";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm p-4">
                <h2 class="text-center mb-4">Insert a Photo of Your License</h2>
                @if (ViewBag.ErrorMessage != null)
                {
                    <div class="alert alert-danger">
                        @ViewBag.ErrorMessage
                    </div>
                }

                <form method="post" action="@Url.Action("AddLicense", "Vehicle")" enctype="multipart/form-data">
                    
                    @Html.AntiForgeryToken()

                    <div>
                        <img id="imgPreview" width="350" height="auto" style="display:none; width: 10em; margin-top: 20px;" />
                    </div>
                    @* shows the choose image input *@
                    <div class="form-group" style="margin-top: 1em">
                        <input type="file" name="imageFile" id="imageFile" class="form-control" onchange="previewImage(event)">
                    </div>

                    <input type="hidden" name="userID" value="@ViewBag.UserID" />
                    <div class="form-group text-center mt-4">
                        <button type="submit" class="btn btn-success">Add</button>
                        <a href="/Vehicle/Index?id=@ViewBag.UserID" class="btn btn-secondary">Back to Vehicles</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        // creates a function to preview the selected image
        function previewImage(event) {
            var reader = new FileReader(); // creates a file reader object
            reader.onload = function () { // an event handler that excecutes when the file is read
                var imgPreview = document.getElementById('imgPreview'); // gets the image element
                imgPreview.src = reader.result; // gives the image the desired src
                imgPreview.style.display = 'block'; // makes the image visible
            };
            reader.readAsDataURL(event.target.files[0]); // reads the first file from input
        }
    </script>
}

WebPresentation/Views/Vehicle/Index.cshtml
@*  <summary> *@
@*      Ellie Wacker *@
@*      Created: 2025-03-27 *@

@*     View for viewing all vehicles
       Last Upaded By:Skyann Heintz *@
@*     Last Updated: 2025-04-04 *@
@*     What Was Changed: Added styling to the document. Moved Add Insurance button to the top of the table on the left side.
           Commented out the old Add Insurance button. Updated the h1 class to say "Your Vehciles" from Index. Adjusted 
           "Activate Vehcile" to Activate

       Last Upaded By: Ellie Wacker *@
@*     Last Updated: 2025-04-04 *@
@*     What Was Changed: I changed the add insurance button to add license and turned activate vehicle into a link to add insurance
        
       Last Upaded By: Skyann Heintz *@
@*     Last Updated: 2025-04-28 *@
@*     What Was Changed: Added styling to buttons

       Last Updated By: Dat Tran
       Last Updated: 2025-04-27
       What was changed: Changed the alert of deactivating a vehicle to a Sweet Alert.

       Last Upaded By: Skyann Heintz *@
@*     Last Updated: 2025-04-30 *@
@*     What Was Changed: Updated "Add Your Vechile" to "Create New Vehicle"


@* </summary> *@

@model IEnumerable<DataDomain.Vehicle>

@{
    ViewData["Title"] = "Index";
}
@* @if (TempData["SuccessMessage"] != null) *@
@* { *@
@*     <div class="alert alert-success"> *@
@*         @TempData["SuccessMessage"] *@
@*     </div> *@
@* } *@

@if (TempData["SuccessMessage"] != null)
{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            if (!sessionStorage.getItem('sweetAlertUpdateVehicleShown')) {
                Swal.fire({
                    icon: 'success',
                    title: 'Done',
                    text: '@TempData["SuccessMessage"]'
                });
                sessionStorage.setItem('sweetAlertUpdateVehicleShown', 'true');
            }
        });
    </script>
    @* Remove the message so it doesn’t persist on refresh *@
    TempData.Remove("SuccessMessage");
}
else
{
    <script>
        // Ensure the flag is reset if there's no success message
        sessionStorage.removeItem('sweetAlertUpdateVehicleShown');
    </script>
}
@if (TempData["AddLicenseSuccess"] != null)
{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            if (!sessionStorage.getItem('sweetAlertAddLicenseShown')) {
                Swal.fire({
                    icon: 'success',
                    title: 'Done',
                    text: '@TempData["AddLicenseSuccess"]'
                });
                sessionStorage.setItem('sweetAlertAddLicenseShown', 'true');
            }
        });
    </script>
    @* Remove the message so it doesn’t persist on refresh *@
    TempData.Remove("AddLicenseSuccess");
}
else
{
    <script>
        // Ensure the flag is reset if there's no success message
        sessionStorage.removeItem('sweetAlertAddLicenseShown');
    </script>
}
@if (TempData["AddSuccess"] != null)
{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            if (!sessionStorage.getItem('sweetAlertAddVehicleShown')) {
                Swal.fire({
                    icon: 'success',
                    title: 'Done',
                    text: '@TempData["AddSuccess"]'
                });
                sessionStorage.setItem('sweetAlertAddVehicleShown', 'true');
            }
        });
    </script>
    @* Remove the message so it doesn’t persist on refresh *@
    TempData.Remove("AddSuccess");
}
else
{
    <script>
        // Ensure the flag is reset if there's no success message
        sessionStorage.removeItem('sweetAlertAddVehicleShown');
    </script>
}
@if (TempData["DeleteSuccess"] != null)
{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            if (!sessionStorage.getItem('sweetAlertDeactivateVehicleShown')) {
                Swal.fire({
                    icon: 'success',
                    title: 'Done',
                    text: '@TempData["DeleteSuccess"]'
                });
                sessionStorage.setItem('sweetAlertDeactivateVehicleShown', 'true');
            }
        });
    </script>
    @* Remove the message so it doesn’t persist on refresh *@
    TempData.Remove("DeleteSuccess");
}
else
{
    <script>
        // Ensure the flag is reset if there's no success message
        sessionStorage.removeItem('sweetAlertDeactivateVehicleShown');
    </script>
}
@if (TempData["AddInsuranceSuccess"] != null)
{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            if (!sessionStorage.getItem('sweetAlertAddInsuranceShown')) {
                Swal.fire({
                    icon: 'success',
                    title: 'Done',
                    text: '@TempData["AddInsuranceSuccess"]'
                });
                sessionStorage.setItem('sweetAlertAddInsuranceShown', 'true');
            }
        });
    </script>
    @* Remove the message so it doesn’t persist on refresh *@
    TempData.Remove("AddInsuranceSuccess");
}
else
{
    <script>
        // Ensure the flag is reset if there's no success message
        sessionStorage.removeItem('sweetAlertAddInsuranceShown');
    </script>
}
<h1 class="text-center">Your Vehicles</h1>

<p>
    <a asp-action="Create" asp-route-id="@ViewBag.UserID" class="btn btn-success">Create New Vehicle</a>
    <a asp-action="AddLicense" asp-route-userID="@ViewBag.UserID" class="btn btn-success float-end">Add Your License</a>

</p>
@if (ViewBag.Message != null)
{
    <div class="alert alert-info text-center"><strong>@ViewBag.Message</strong></div>
}
else
{
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead class="thead-dark">
                <tr>
                    <th class="header">Vin Number</th>
                    <th class="header">
                        @Html.DisplayNameFor(model => model.Active)
                    </th>
                    <th class="header">
                        @Html.DisplayNameFor(model => model.Color)
                    </th>
                    <th class="header">
                        @Html.DisplayNameFor(model => model.Year)
                    </th>
                    <th class="header">
                        License Plate Number
                    </th>
                    <th class="header">
                        Insurance Status
                    </th>
                    <th class="header">
                        @Html.DisplayNameFor(model => model.Make)
                    </th>
                    <th class="header">
                        @Html.DisplayNameFor(model => model.Model)
                    </th>
                    <th class="header">
                        Number Of Seats
                    </th>
                    <th class="header">
                        Can Transport
                    </th>
                    <th class="header"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.VehicleID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Active)
                        </td>
                        <td>
                            <p class="text-capitalize">@Html.DisplayFor(modelItem => item.Color)</p>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Year)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LicensePlateNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InsuranceStatus)
                        </td>
                        <td>
                            <p class="text-capitalize">@Html.DisplayFor(modelItem => item.Make)</p>
                        </td>
                        <td>
                            <p class="text-capitalize">@Html.DisplayFor(modelItem => item.Model)</p>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumberOfSeats)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TransportUtility)
                        </td>
                        <td class="text-center">
                            <div class="d-flex flex-wrap justify-content-center gap-2">
                                @Html.ActionLink("Edit", "Edit", new { id = item.VehicleID, userID = ViewBag.UserID }, new { @class = "btn btn-warning btn-sm" })
                                @if (item.Active == false)
                                {
                                    <div class="d-flex justify-content-center gap-2">
                                        @Html.ActionLink("Activate", "AddInsurance", new { vehicleID = item.VehicleID, userID = ViewBag.UserID }, new { @class = "btn btn-success btn-sm" })
                                    </div>
                                }
                                @* This makes a pop up confirm box *@
                                @if (item.Active == true)
                                {
                                    <a href="@Url.Action("Deactivate", new { id = item.VehicleID, userID = item.UserID })"
                                       class="btn btn-danger btn-sm" id="deleteButton">
                                        Deactivate
                                    </a>
                                    <script>
                                        document.getElementById("deleteButton").addEventListener("click", function (e) {
                                            e.preventDefault(); // @*This prevents the link from immediately navigating away*@ 

                                                    Swal.fire({
                                                title: 'Are you sure?',
                                                text: "You won't be able to revert this!",
                                                icon: 'warning',
                                                showCancelButton: true,
                                                confirmButtonColor: '#d33',
                                                cancelButtonColor: '#3085d6',
                                                confirmButtonText: 'Yes, deactivate it.'
                                            }).then((result) => {
                                                if (result.isConfirmed) {
                                        @*Manually redirect the user to the Deactivate URL if confirmed*@
                                                    window.location.href = this.href;
                                                }
                                        @*If they cancel, nothing happens. Stay on the page.*@
                                            });
                                        });
                                    </script>
                                }
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div>

        @* <a href="@Url.Action("UserProfile", "User", new { email = ViewBag.Email })"class="btn btn-secondary">Back to Profile</a> *@

    </div>

}